### ISSUE TITLE
页面跳转问题

### ISSUE THREAD

**Issue by junwen0814** [VictorChow/SmartGo#1]
从A页面跳转到B页面，如果我看B页面代码的时候，想知道B页面有从哪些地方跳转过来的，怎么看？

**Comment by VictorChow** [comment]
SmartGo.from(this)
                .toXXXActivity()
                ...
在SmartGo类搜 toXXXActivity() 这个方法,  find usages

**Comment by junwen0814** [comment]
每次都必须Rebuild吗，小项目还好，大项目Rebuild一次好慢，不过还是挺方便的

**Comment by VictorChow** [comment]
我看看哈，这个先保持open吧

**Comment by VictorChow** [comment]
现在ok了，把版本改成1.2.0试一下吧
